### ISSUE TITLE
Regarding the output issue of ONNX model

### ISSUE THREAD

**Issue by zhaoyangwei123** [lindevs/yolov8-face#2]
Hello author, thank you very much for your open source work. However, when using onnx for facial recognition inference, I need to use the output of the YOLOV8 facial detection model as input for subsequent models. However, through the onnx viewer, I observed that the output of the facial detection model is 1 * 80 * 20 * 20. May I ask why it is not the (x, y, w, h) coordinates? Facial detection should obtain the position of the detection box.

**Comment by lindevs** [comment]
Hi. The ONNX models available on the [releases page](https://github.com/lindevs/yolov8-face/releases) produce an output with the shape [1, 5, 8400]. You can use the Netron application to inspect the model structure. For processing the model output and extracting the (x, y, w, h) coordinates, refer to the [OpenCV DNN example](https://github.com/lindevs/yolov8-face/blob/master/examples/opencv-dnn-python/main.py).
